version: '3'
services:
  client:
    build: 
      context: ./frontend
    image: loosescrew/whine_client
    restart: always
    ports:
      - "3000:3000"
    networks:
      - webappnetwork
  server:
    build: 
      context: ./backend
    image: loosescrew/whine_server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - webappnetwork
  database:
    image: mongo
    restart: always
    volumes:
      - /database/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge