version: '3'
services:
  # client:
  #   build: 
  #     context: ./frontend
  #   image: loosescrew/whine_client:v0.2
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - webappnetwork
  # server:
  #   build: 
  #     context: ./backend
  #   image: loosescrew/whine_server:v0.2
  #   restart: always
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - webappnetwork
  app_server:
    build: 
      context: ./backend
    image: loosescrew/whine_app_server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - webappnetwork
  database:
    image: mongo
    restart: always
    volumes:
      - /database/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge